services:
  - type: web
    name: elecciones
    env: python
    pythonVersion: 3.12.5
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread --threads 4 --timeout 120 -b 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: API_BASE
        value: https://resultados.mininterior.gob.ar/api
      # - key: BEARER_TOKEN
      #   sync: false
